name: Test PR

on: pull_request

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run gradle check
        run: ./gradlew clean check
